version: "3.7"
services:
  soda-core-mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=sodacore
      - MYSQL_USER=sodacore
      - MYSQL_PASSWORD=sodacore
      - MYSQL_ROOT_PASSWORD=sodacore
