version: "3.7"
services:
  soda-sql-sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1!
